name: messenger
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^2.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
#  cloud_firestore: 0.13.4
  firebase_auth: any
#  firebase_analytics: any
#  firebase_database: any
#  firebase_storage: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
