name: messenger
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^2.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
  firebase_auth: any
  qr_flutter: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
