name: messenger
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^2.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
  firebase_core: any
  firebase_auth: any
  qr_flutter: any
  shared_preferences: any
  encrypt: any
  device_info: any
  qr_mobile_vision: 0.3.1
  firebase_messaging: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
