name: messenger
description: Encrypted messenger

version: 1.0.0+1

environment:
  sdk: ^2.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
#  firebase_messaging: any
  qr_flutter: any
  shared_preferences: any
  encrypt: any
  device_info: any
  qr_mobile_vision: any
  demoji: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
